[workspace]
resolver = "2"
members = [
    "example_parsing",
]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
nom = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"