[package]
name = "examples_common"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "example_logging"
path = "examples/example_logging.rs"

[dependencies]
parking_lot.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
